config/routes.rb
Practice::Application.routes.draw do
  resources :messages

  resources :chats

  resources :albums

  resources :comments

  resources :reviews

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :homes

  match "", to:  "chats#index", constraints: { subdomain: "chat" }

  match '/pusher/auth' => 'pusher#auth'

  root :to => 'homes#index'

end

app/models/chat.rb
class Chat < ActiveRecord::Base
	attr_accessible :message
	validates_presence_of :message
	validates_length_of :message, :minimum => 10
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  # GET /chats
  # GET /chats.json
  skip_before_filter :authenticate_user!
  def index
    request.subdomain
    @chats = Chat.all
    #render layout: false
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
    @chat = Chat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chat }
    end
  end

  # GET /chats/new
  # GET /chats/new.json
  def new
    @chat = Chat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chat }
    end
  end

  # GET /chats/1/edit
  def edit
    @chat = Chat.find(params[:id])
  end

  # POST /chats
  # POST /chats.json
  def create
    Pusher.app_id = PUSHER_APP_ID
    Pusher.key = PUSHER_KEY
    Pusher.secret = PUSHER_SECRET
    @chat = Chat.create!(params[:chat])
    x = render_to_string(:partial => "chat", locals: {chat: @chat})
    Pusher["private-user-#{current_user.try(:id)}"].trigger("new-notification", x)
  end

  # PUT /chats/1
  # PUT /chats/1.json
  def update
    @chat = Chat.find(params[:id])

    respond_to do |format|
      if @chat.update_attributes(params[:chat])
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat = Chat.find(params[:id])
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to chats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_chat.html.erb
<% p chat %>
<% p @chat %>
<% chat = @chat.nil? ? chat : @chat %>
<li>
  <span class="created_at"><%= chat.created_at.strftime("%H:%M") %></span>
  <%= chat.message %>
</li>

app/views/chats/_form.html.haml
= form_for @chat do |f|
  -if @chat.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chat.errors.count, "error")} prohibited this chat from being saved:"
      %ul
        - @chat.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :message
    = f.text_field :message
  .actions
    = f.submit 'Save'

app/views/chats/_notification.html.haml
Tets notification

app/views/chats/create.js.erb
$("#new_chat")[0].reset();

app/views/chats/edit.html.haml
%h1 Editing chat

= render 'form'

= link_to 'Show', @chat
\|
= link_to 'Back', chats_path

app/views/chats/index.html.haml
%h1 Public Chat
%ul#chat_room
  = render @chats
= form_for Chat.new, :remote => true do |f|
  = f.text_field :message
  = f.submit "Send"
%nav
  %ul
    %li
      %a{:href => "#start"} 1
    %li
      %a{:href => "#description"} Home
    %li
      %a{:href => "#syntax"} Movies
    %li
      %a{:href => "#scrollbar"} Photos
    %li
      %a{:href => "#rotations"} 5
    %li
      %a{:href => "#rotations-rotated"} 6
    %li
      %a{:href => "#source"} 7
    %li
      %a{:href => "#follow"} 8
.settings
  %a.show-path{:href => ""} Show Path
.wrapper
  .demo
    %h1 Welcome
  .description
    %h1= link_to "Home", homes_path
  .syntax
    %h1= link_to "Movie Reviews", reviews_path
  .scrollbar
    %h1 Photos
  .rotations
    %span.big{:style => "font-size: 2em;"} It also does rotations
    %span.upside-down.big in browsers.
  .source
    %span.big
      It's available with documentation on
      = succeed "." do
        %a{:href => "https://github.com/JoelBesada/scrollpath"} GitHub
      %span
  .follow
    %span.big
      Feel free to
      %a{:href => "https://twitter.com/JoelBesada"} follow me
      on Twitter. You can also be
      %span.count a kind person and
      %a.tweet{:href => "https://twitter.com/intent/tweet?original_referer=https%3A%2F%2Ftwitter.com%2Fabout%2Fresources%2Fbuttons&source=tweetbutton&text=jQuery%20Scroll%20Path%20Plugin&url=http%3A%2F%2Fjoelb.me%2Fscrollpath%2F&via=JoelBesada"} tweet
      this.

app/views/chats/new.html.haml
%h1 New chat

= render 'form'

= link_to 'Back', chats_path

app/views/chats/show.html.haml
%p#notice= notice

%p
  %b Message:
  = @chat.message

= link_to 'Edit', edit_chat_path(@chat)
\|
= link_to 'Back', chats_path