config/routes.rb
Practice::Application.routes.draw do
  resources :messages

  resources :chats

  resources :albums

  resources :comments

  resources :reviews

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :homes

  match "", to:  "chats#index", constraints: { subdomain: "chat" }

  match '/pusher/auth' => 'pusher#auth'

  root :to => 'homes#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_attached_file :photo, :styles => { :small => "150x150#", :medium => "50x55" }
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.haml
= form_for @album do |f|
  -if @album.errors.any?
    #error_explanation
      %h2= "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
      %ul
        - @album.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :photo
    %br/
    = f.file_field :photo
  .actions
    = f.submit 'Save'

app/views/albums/edit.html.haml
%h1 Editing album

= render 'form'

= link_to 'Show', @album
\|
= link_to 'Back', albums_path

app/views/albums/index.html.haml
%h1 Listing albums

%table
  %tr
    %th Movie
    %th Description
    %th Title
    %th Actions

  - @albums.each do |album|
    %tr
      %td= image_tag album.photo(:medium)
      %td= album.description
      %td= album.name
      %td
        = link_to 'Show', album
        = link_to 'Edit', edit_album_path(album)
        = link_to 'Destroy', album, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Album', new_album_path

app/views/albums/new.html.haml
%h1 New album

= render 'form'

= link_to 'Back', albums_path

app/views/albums/show.html.haml
%p#notice= notice

%p
  = image_tag @album.photo
%p
  %b Name:
  = @album.name
%p
  %b Description:
  = @album.description

= link_to 'Edit', edit_album_path(@album)
\|
= link_to 'Back', albums_path